services:
  db:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: taller
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - taller_net

  api:
    build:
      context: ./api
    container_name: flask_api
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - taller_net

  web:
    build:
      context: ./web
    container_name: web_frontend
    ports:
      - "8080:80"
    networks:
      - taller_net

  automation:
    build:
      context: ./scripts
    container_name: automation_tools
    volumes:
      - ./scripts:/scripts
      - ./backups:/backups
    networks:
      - taller_net
    entrypoint: ["/bin/bash", "-c", "while true; do /scripts/backup.sh; sleep 86400; done"]

volumes:
  db_data:

networks:
  taller_net:
